# Identificación del proyecto en SonarCloud
sonar.projectKey=TomiDuarte_segundo-parcial
sonar.organization=tomiduarte

# Información del proyecto
sonar.projectName=segundo-parcial
sonar.projectVersion=1.0.0

# Código fuente y tests
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11

# Reporte de cobertura (lo genera pytest)
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones
sonar.exclusions=**/__init__.py,venv/**,**/*.pyc

# Codificación
sonar.sourceEncoding=UTF-8